
networks:
  web:
    external: true
    name: server-web

services:

  foundry:
    image: felddy/foundryvtt:${FOUNDRY_VERSION}
    volumes:
      - ${DATA_PATH}/Data/${SUBDOMAIN}:/data/Data
      - ${DATA_PATH}/Config/${SUBDOMAIN}:/data/Config
      - ${DATA_PATH}/Logs/${SUBDOMAIN}:/data/Logs
    environment:
      - FOUNDRY_USERNAME=${FOUNDRY_USERNAME}
      - FOUNDRY_PASSWORD=${FOUNDRY_PASSWORD}
      - FOUNDRY_HOSTNAME=${SUBDOMAIN}.${HOST_NAME}
      - FOUNDRY_TELEMETRY=false
      - FOUNDRY_PROXY_SSL=true
      - FOUNDRY_PROXY_PORT=443
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SUBDOMAIN}.rule=Host(`${SUBDOMAIN}.${HOST_NAME}`)"
      - "traefik.http.routers.${SUBDOMAIN}.entrypoints=websecure"
      - "traefik.http.routers.${SUBDOMAIN}.tls.certresolver=myresolver"
      - "traefik.http.routers.${SUBDOMAIN}.middlewares=authentik@docker"
      - "traefik.http.services.${SUBDOMAIN}.loadbalancer.server.port=30000"
      - "traefik.docker.network=server-web"
    networks:
      - web
